PREFIX : <http://example.org/>

SELECT ?person ?name ?country WHERE {
  ?person a :Human ;
    :name ?name ;
    :birthDate ?birthDate ;
    :birthPlace ?birthPlace .
  ?birthPlace :country ?country
}